import React,{useEffect,useState} from 'react';
import {Tag,RefreshCw,Trash2,Power,PowerOff,AlertTriangle} from 'lucide-react';
import {useToast} from './ui/Toast.tsx';

type Coupon={id:string;marketplace:string;code:string;description?:string;discount_type?:string;discount_value?:number;expires_at?:string;source_url?:string;is_active?:boolean};
type Props={apiFetch:(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>};
export const CouponsTab:React.FC<Props>=({apiFetch})=>{
 const toast=useToast(); const [items,setItems]=useState<Coupon[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [marketplace,setMarketplace]=useState<'SHOPEE'|'MERCADOLIVRE'>('SHOPEE');
 const load=async()=>{setLoading(true);try{const r=await apiFetch('/api/coupons?marketplace='+marketplace);const d=await r.json().catch(()=>[]);if(!r.ok)throw new Error(d.error||'Não foi possível carregar cupons.');setItems(Array.isArray(d)?d:[]);}catch(e){toast('error','Cupons',(e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[marketplace]);
 const action=async(id:string,method:string,path:string)=>{setBusy(id);try{const r=await apiFetch(path,{method});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Operação não concluída.');await load();toast('success','Cupom atualizado','O estado foi salvo.')}catch(e){toast('error','Cupom',(e as Error).message)}finally{setBusy(null)}};
 return <div className="mx-auto max-w-7xl space-y-5"><div className="rounded-lg border border-border bg-surface-1 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-lg font-bold text-text">Cupons</h2><p className="mt-1 text-sm text-muted">Controle os cupons encontrados e evite usar códigos expirados.</p></div><div className="flex gap-2"><select value={marketplace} onChange={e=>setMarketplace(e.target.value as any)} className="rounded-md border border-border-strong bg-surface-2 px-3 py-2 text-sm text-text"><option value="SHOPEE">Shopee</option><option value="MERCADOLIVRE">Mercado Livre</option></select><button onClick={()=>void load()} className="rounded-md border border-border-strong bg-surface-2 p-2 text-muted hover:text-text"><RefreshCw className="h-4 w-4"/></button></div></div></div>{loading?<div className="h-48 animate-pulse rounded-lg bg-surface-1"/>:items.length===0?<div className="rounded-lg border border-dashed border-border p-10 text-center"><Tag className="mx-auto h-7 w-7 text-subtle"/><p className="mt-2 font-semibold text-text">Nenhum cupom ativo encontrado</p><p className="mt-1 text-sm text-muted">Os cupons podem ser registrados automaticamente a partir das ofertas.</p></div>:<div className="grid gap-4 md:grid-cols-2">{items.map(c=>{const expired=Boolean(c.expires_at&&new Date(c.expires_at).getTime()<=Date.now());return <div key={c.id} className="rounded-lg border border-border bg-surface-1 p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Tag className="h-4 w-4 text-brand-300"/><code className="font-bold text-text">{c.code}</code></div><p className="mt-2 text-sm text-muted">{c.description||'Cupom sem descrição.'}</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${expired?'bg-rose-500/10 text-rose-300':'bg-brand-500/10 text-brand-300'}`}>{expired?'Expirado':'Ativo'}</span></div>{c.expires_at&&<div className={`mt-3 flex items-center gap-1 text-xs ${expired?'text-rose-300':'text-subtle'}`}>{expired&&<AlertTriangle className="h-3.5 w-3.5"/>}Validade: {new Date(c.expires_at).toLocaleString('pt-BR')}</div>}<div className="mt-4 flex justify-end gap-2"><button disabled={busy!==null} onClick={()=>void action(c.id,'PATCH','/api/coupons/'+encodeURIComponent(c.id))} className="inline-flex items-center gap-1 rounded-md border border-border-strong px-3 py-2 text-xs font-semibold text-muted hover:text-text">{c.is_active?<PowerOff className="h-3.5 w-3.5"/>:<Power className="h-3.5 w-3.5"/>}{c.is_active?'Desativar':'Ativar'}</button><button disabled={busy!==null} onClick={()=>{if(confirm('Excluir este cupom?'))void action(c.id,'DELETE','/api/coupons/'+encodeURIComponent(c.id))}} className="inline-flex items-center gap-1 rounded-md border border-rose-500/20 bg-rose-500/10 px-3 py-2 text-xs font-semibold text-rose-300"><Trash2 className="h-3.5 w-3.5"/>Excluir</button></div></div>})}</div>}</div>;
};
