import React,{useState} from 'react';
import { Users, Radio, Plus, RefreshCw, Clock, ChevronDown } from 'lucide-react';
import type { Destination, MarketplaceType } from '../types/affiliate.ts';
import { useToast } from './ui/Toast.tsx';

interface Props{destinations:Destination[];onAddDestination:(dest:Partial<Destination>)=>Promise<void>;apiFetch:(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>;}
export const DestinationsTab:React.FC<Props>=({destinations,onAddDestination,apiFetch})=>{
 const toast=useToast();
 const [initialLoading,setInitialLoading]=useState(true); React.useEffect(()=>{const t=window.setTimeout(()=>setInitialLoading(false),300);return()=>window.clearTimeout(t)},[]);
 const [show,setShow]=useState(false),[name,setName]=useState(''),[type,setType]=useState<'WHATSAPP_GROUP'|'WHATSAPP_CHANNEL'>('WHATSAPP_GROUP'),[identifier,setIdentifier]=useState(''),[keywords,setKeywords]=useState('Pokémon, TCG, Gamer'),[frequency,setFrequency]=useState(45),[start,setStart]=useState('08:00'),[end,setEnd]=useState('22:00'),[marketplaces,setMarketplaces]=useState<MarketplaceType[]>(['SHOPEE','MERCADOLIVRE']),[groups,setGroups]=useState<any[]>([]),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await apiFetch('/api/whatsapp/groups');const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível carregar os grupos.');setGroups(Array.isArray(d)?d:[]);}catch(e){toast('error','Não foi possível carregar os grupos',(e as Error).message);}finally{setLoading(false);}};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!name.trim()||!identifier.trim()){toast('error','Grupo não selecionado','Escolha um grupo do WhatsApp.');return;}setSaving(true);try{await onAddDestination({name,type,identifier,marketplaces,keywords:keywords.split(',').map(x=>x.trim()).filter(Boolean).slice(0,5),frequency_minutes:Number(frequency),time_start:start,time_end:end,priority:'HIGH',is_active:true});setShow(false);setName('');setIdentifier('');}catch(err){toast('error','Não foi possível adicionar o grupo',(err as Error).message);}finally{setSaving(false);}};
 const toggle=(m:MarketplaceType)=>setMarketplaces(v=>v.includes(m)?(v.length>1?v.filter(x=>x!==m):v):[...v,m]);
 if(initialLoading) return <div className="w-full space-y-6" aria-busy="true"><div className="h-24 rounded-lg bg-surface-1 animate-pulse"/><div className="grid gap-4 md:grid-cols-2">{Array.from({length:2}).map((_,i)=><div key={i} className="h-44 rounded-lg bg-surface-1 animate-pulse"/>)}</div>;
 return <div className="w-full space-y-6">
  <div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-brand-300">Automação</p><h1 className="mt-1 text-3xl font-bold text-text">Onde suas ofertas serão enviadas?</h1><p className="mt-2 text-sm text-muted">Escolha os grupos. O sistema cuida do envio automaticamente.</p></div><button onClick={()=>setShow(v=>!v)} className="rounded-md bg-brand-500 px-4 py-3 text-sm font-bold text-bg hover:bg-brand-400"><Plus className="mr-1.5 inline h-4 w-4"/>{show?'Fechar':'Adicionar grupo'}</button></div>
  {show&&<form onSubmit={submit} className="rounded-lg border border-border bg-surface-1 p-6 sm:p-8">
   <div className="mb-6"><h2 className="font-semibold text-text">Novo grupo</h2><p className="mt-1 text-xs text-subtle">Poucas configurações. Você poderá ajustar depois.</p></div>
   <div className="grid gap-5 md:grid-cols-2">
    <div><label className="mb-1.5 block text-sm text-text">Nome</label><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Achadinhos Pokémon" className="w-full rounded-md border border-border-strong bg-bg px-4 py-3 text-sm text-text outline-none focus:border-brand-500"/></div>
    <div><label className="mb-1.5 block text-sm text-text">Grupo do WhatsApp</label><div className="flex gap-2"><select required value={identifier} onChange={e=>setIdentifier(e.target.value)} className="min-w-0 flex-1 rounded-md border border-border-strong bg-bg px-4 py-3 text-sm text-text outline-none focus:border-brand-500"><option value="">Selecione um grupo</option>{groups.map(g=><option key={g.id} value={g.id}>{g.subject||g.id}</option>)}</select><button type="button" onClick={load} className="rounded-md border border-border-strong px-3 text-text hover:bg-surface-2" title="Atualizar grupos">{loading?<RefreshCw className="h-4 w-4 animate-spin"/>:<RefreshCw className="h-4 w-4"/>}</button></div><p className="mt-1.5 text-xs text-subtle">Se a lista estiver vazia, conecte o WhatsApp primeiro.</p></div>
    <div><label className="mb-1.5 block text-sm text-text">O que procurar</label><input value={keywords} onChange={e=>setKeywords(e.target.value)} className="w-full rounded-md border border-border-strong bg-bg px-4 py-3 text-sm text-text outline-none focus:border-brand-500"/><p className="mt-1.5 text-xs text-subtle">Até 5 temas separados por vírgula.</p></div>
    <div><label className="mb-1.5 block text-sm text-text">Marketplaces</label><div className="flex gap-2">{(['SHOPEE','MERCADOLIVRE'] as MarketplaceType[]).map(m=><button type="button" key={m} onClick={()=>toggle(m)} className={"rounded-md border px-3 py-2 text-sm font-semibold "+(marketplaces.includes(m)?'border-brand-500/30 bg-brand-500/10 text-brand-200':'border-border-strong text-subtle')}>{m==='SHOPEE'?'Shopee':'Mercado Livre'}</button>)}</div></div>
    <div className="md:col-span-2 rounded-md border border-border p-4"><div className="flex items-center gap-2 text-sm font-semibold text-text"><ChevronDown className="h-4 w-4 text-subtle"/>Mais opções</div><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm text-muted">Intervalo mínimo<input type="number" min="5" max="1440" value={frequency} onChange={e=>setFrequency(Number(e.target.value))} className="mt-1 w-full rounded-md border border-border-strong bg-bg px-3 py-2 text-sm text-text"/></label><label className="text-sm text-muted">Começar às<input type="time" value={start} onChange={e=>setStart(e.target.value)} className="mt-1 w-full rounded-md border border-border-strong bg-bg px-3 py-2 text-sm text-text"/></label><label className="text-sm text-muted">Parar às<input type="time" value={end} onChange={e=>setEnd(e.target.value)} className="mt-1 w-full rounded-md border border-border-strong bg-bg px-3 py-2 text-sm text-text"/></label></div></div></div>
   </div>
   <div className="mt-6 flex justify-end gap-2 border-t border-border pt-5"><button type="button" onClick={()=>setShow(false)} className="rounded-md px-4 py-3 text-sm text-muted">Cancelar</button><button disabled={saving} className="rounded-md bg-brand-500 px-5 py-3 text-sm font-bold text-bg">{saving?'Salvando...':'Adicionar grupo'}</button></div>
  </form>}
  {destinations.length===0?<div className="rounded-lg border border-dashed border-border p-12 text-center"><Users className="mx-auto h-10 w-10 text-subtle"/><h2 className="mt-4 font-semibold text-text">Nenhum grupo configurado</h2><p className="mx-auto mt-2 max-w-md text-xs text-subtle">Adicione seu primeiro grupo e escolha os temas. Depois a automação trabalha sozinha.</p><button onClick={()=>setShow(true)} className="mt-5 rounded-md bg-surface-2 px-4 py-2.5 text-sm font-semibold text-text">Adicionar primeiro grupo</button></div>:
  <div className="grid gap-4 md:grid-cols-2">{destinations.map(d=><div key={d.id} className="rounded-lg border border-border bg-surface-1 p-5"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-md bg-brand-500/10 text-brand-300">{d.type==='WHATSAPP_GROUP'?<Users className="h-5 w-5"/>:<Radio className="h-5 w-5"/>}</div><div><h3 className="font-semibold text-text">{d.name}</h3><p className="mt-0.5 text-xs text-subtle">{d.type==='WHATSAPP_GROUP'?'Grupo WhatsApp':'Canal'}</p></div></div><span className="rounded-full bg-brand-500/10 px-2 py-1 text-sm font-semibold text-brand-200">Ativo</span></div><div className="mt-5 flex flex-wrap gap-2">{d.keywords?.map(k=><span key={k} className="rounded-full bg-surface-2 px-2.5 py-1 text-sm text-text">{k}</span>)}</div><div className="mt-5 flex items-center justify-between border-t border-border pt-4 text-xs text-subtle"><span><Clock className="mr-1 inline h-3.5 w-3.5"/>A cada {d.frequency_minutes} min</span><span>{d.marketplaces?.join(' · ')}</span></div></div>)}</div>}
 </div>;
};