import React,{useState} from 'react';
import { Users, Radio, Plus, RefreshCw, Clock, ChevronDown } from 'lucide-react';
import type { Destination, MarketplaceType } from '../types/affiliate.ts';

interface Props{destinations:Destination[];onAddDestination:(dest:Partial<Destination>)=>Promise<void>;apiFetch:(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>;}
export const DestinationsTab:React.FC<Props>=({destinations,onAddDestination,apiFetch})=>{
 const [show,setShow]=useState(false),[name,setName]=useState(''),[type,setType]=useState<'WHATSAPP_GROUP'|'WHATSAPP_CHANNEL'>('WHATSAPP_GROUP'),[identifier,setIdentifier]=useState(''),[keywords,setKeywords]=useState('Pokémon, TCG, Gamer'),[frequency,setFrequency]=useState(45),[start,setStart]=useState('08:00'),[end,setEnd]=useState('22:00'),[marketplaces,setMarketplaces]=useState<MarketplaceType[]>(['SHOPEE','MERCADOLIVRE']),[groups,setGroups]=useState<any[]>([]),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await apiFetch('/api/whatsapp/groups');const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível carregar os grupos.');setGroups(Array.isArray(d)?d:[]);}catch(e){alert((e as Error).message);}finally{setLoading(false);}};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!name.trim()||!identifier.trim())return alert('Escolha um grupo do WhatsApp.');setSaving(true);try{await onAddDestination({name,type,identifier,marketplaces,keywords:keywords.split(',').map(x=>x.trim()).filter(Boolean).slice(0,5),frequency_minutes:Number(frequency),time_start:start,time_end:end,priority:'HIGH',is_active:true});setShow(false);setName('');setIdentifier('');}catch(err){alert((err as Error).message);}finally{setSaving(false);}};
 const toggle=(m:MarketplaceType)=>setMarketplaces(v=>v.includes(m)?(v.length>1?v.filter(x=>x!==m):v):[...v,m]);
 return <div className="mx-auto max-w-5xl space-y-6">
  <div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-emerald-400">Automação</p><h1 className="mt-1 text-3xl font-bold text-white">Onde suas ofertas serão enviadas?</h1><p className="mt-2 text-sm text-slate-400">Escolha os grupos. O sistema cuida do envio automaticamente.</p></div><button onClick={()=>setShow(v=>!v)} className="rounded-xl bg-emerald-500 px-4 py-3 text-sm font-bold text-slate-950 hover:bg-emerald-400"><Plus className="mr-1.5 inline h-4 w-4"/>{show?'Fechar':'Adicionar grupo'}</button></div>
  {show&&<form onSubmit={submit} className="rounded-3xl border border-slate-800 bg-slate-900 p-6 sm:p-8">
   <div className="mb-6"><h2 className="font-semibold text-white">Novo grupo</h2><p className="mt-1 text-xs text-slate-500">Poucas configurações. Você poderá ajustar depois.</p></div>
   <div className="grid gap-5 md:grid-cols-2">
    <div><label className="mb-1.5 block text-xs text-slate-300">Nome</label><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Achadinhos Pokémon" className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm text-white outline-none focus:border-emerald-500"/></div>
    <div><label className="mb-1.5 block text-xs text-slate-300">Grupo do WhatsApp</label><div className="flex gap-2"><select required value={identifier} onChange={e=>setIdentifier(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm text-white outline-none focus:border-emerald-500"><option value="">Selecione um grupo</option>{groups.map(g=><option key={g.id} value={g.id}>{g.subject||g.id}</option>)}</select><button type="button" onClick={load} className="rounded-xl border border-slate-700 px-3 text-slate-300 hover:bg-slate-800" title="Atualizar grupos">{loading?<RefreshCw className="h-4 w-4 animate-spin"/>:<RefreshCw className="h-4 w-4"/>}</button></div><p className="mt-1.5 text-[11px] text-slate-500">Se a lista estiver vazia, conecte o WhatsApp primeiro.</p></div>
    <div><label className="mb-1.5 block text-xs text-slate-300">O que procurar</label><input value={keywords} onChange={e=>setKeywords(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm text-white outline-none focus:border-emerald-500"/><p className="mt-1.5 text-[11px] text-slate-500">Até 5 temas separados por vírgula.</p></div>
    <div><label className="mb-1.5 block text-xs text-slate-300">Marketplaces</label><div className="flex gap-2">{(['SHOPEE','MERCADOLIVRE'] as MarketplaceType[]).map(m=><button type="button" key={m} onClick={()=>toggle(m)} className={"rounded-xl border px-3 py-2 text-xs font-semibold "+(marketplaces.includes(m)?'border-emerald-500/30 bg-emerald-500/10 text-emerald-300':'border-slate-700 text-slate-500')}>{m==='SHOPEE'?'Shopee':'Mercado Livre'}</button>)}</div></div>
    <details className="md:col-span-2 rounded-xl border border-slate-800 p-4"><summary className="cursor-pointer text-xs font-semibold text-slate-300"><ChevronDown className="mr-1 inline h-3 w-3"/>Mais opções</summary><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-xs text-slate-400">Intervalo mínimo<input type="number" min="5" max="1440" value={frequency} onChange={e=>setFrequency(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white"/></label><label className="text-xs text-slate-400">Começar às<input type="time" value={start} onChange={e=>setStart(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white"/></label><label className="text-xs text-slate-400">Parar às<input type="time" value={end} onChange={e=>setEnd(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white"/></label></div></details>
   </div>
   <div className="mt-6 flex justify-end gap-2 border-t border-slate-800 pt-5"><button type="button" onClick={()=>setShow(false)} className="rounded-xl px-4 py-3 text-sm text-slate-400">Cancelar</button><button disabled={saving} className="rounded-xl bg-emerald-500 px-5 py-3 text-sm font-bold text-slate-950">{saving?'Salvando...':'Adicionar grupo'}</button></div>
  </form>}
  {destinations.length===0?<div className="rounded-3xl border border-dashed border-slate-800 p-12 text-center"><Users className="mx-auto h-10 w-10 text-slate-600"/><h2 className="mt-4 font-semibold text-white">Nenhum grupo configurado</h2><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">Adicione seu primeiro grupo e escolha os temas. Depois a automação trabalha sozinha.</p><button onClick={()=>setShow(true)} className="mt-5 rounded-xl bg-slate-800 px-4 py-2.5 text-sm font-semibold text-white">Adicionar primeiro grupo</button></div>:
  <div className="grid gap-4 md:grid-cols-2">{destinations.map(d=><div key={d.id} className="rounded-3xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-400">{d.type==='WHATSAPP_GROUP'?<Users className="h-5 w-5"/>:<Radio className="h-5 w-5"/>}</div><div><h3 className="font-semibold text-white">{d.name}</h3><p className="mt-0.5 text-xs text-slate-500">{d.type==='WHATSAPP_GROUP'?'Grupo WhatsApp':'Canal'}</p></div></div><span className="rounded-full bg-emerald-500/10 px-2 py-1 text-[10px] font-semibold text-emerald-300">Ativo</span></div><div className="mt-5 flex flex-wrap gap-2">{d.keywords?.map(k=><span key={k} className="rounded-full bg-slate-800 px-2.5 py-1 text-[10px] text-slate-300">{k}</span>)}</div><div className="mt-5 flex items-center justify-between border-t border-slate-800 pt-4 text-xs text-slate-500"><span><Clock className="mr-1 inline h-3.5 w-3.5"/>A cada {d.frequency_minutes} min</span><span>{d.marketplaces?.join(' · ')}</span></div></div>)}</div>}
 </div>;
};