import React from 'react';
import { LayoutDashboard, Search, Users, Send, MoreHorizontal, LogOut, Share2, Settings2, Store, ClipboardCheck, BookOpen } from 'lucide-react';
import type { MarketplaceAccount } from '../types/affiliate.ts';
import { Dropdown } from './ui/Dropdown.tsx';
interface HeaderProps { activeTab:string; setActiveTab:(tab:string)=>void; accounts:MarketplaceAccount[]; onRunTests:()=>void; isTestingSuite:boolean; onLogout:()=>void; }
export const Header:React.FC<HeaderProps>=({activeTab,setActiveTab,accounts,onRunTests,isTestingSuite,onLogout})=>{
 const items=[{id:'dashboard',label:'Início',icon:LayoutDashboard},{id:'offers',label:'Ofertas',icon:Search},{id:'destinations',label:'WhatsApp',icon:Users},{id:'queue',label:'Envios',icon:Send}];
 return <header className="sticky top-0 z-40 border-b border-border/80 bg-bg/95 backdrop-blur"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="flex min-h-16 items-center gap-4">
 <button onClick={()=>setActiveTab('dashboard')} className="flex min-w-0 shrink-0 items-center gap-3 rounded-md text-left outline-none focus-visible:ring-4 focus-visible:ring-brand-500/15"><div className="flex h-9 w-9 items-center justify-center rounded-md bg-brand-500 text-bg"><Share2 className="h-4 w-4"/></div><div className="hidden md:block"><div className="font-bold tracking-tight text-text">WhatsappAfiliado</div><div className="text-xs text-subtle">Automação de ofertas</div></div></button>
 <nav className="ml-auto flex min-w-0 items-center gap-1">{items.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setActiveTab(id)} className={['inline-flex shrink-0 items-center gap-2 rounded-md px-3 py-2 text-sm font-semibold transition-colors',activeTab===id?'bg-brand-500 text-bg':'text-muted hover:bg-surface-2 hover:text-text'].join(' ')}><Icon className="h-4 w-4"/><span className="hidden sm:inline">{label}</span></button>)}
 <button onClick={()=>setActiveTab('setup')} className={['inline-flex shrink-0 items-center gap-2 rounded-md px-3 py-2 text-sm font-semibold transition-colors',activeTab==='setup'?'bg-surface-3 text-text':'text-muted hover:bg-surface-2 hover:text-text'].join(' ')}><Settings2 className="h-4 w-4"/><span className="hidden sm:inline">Configurar</span></button>
 <Dropdown label="Mais opções" trigger={<span className="inline-flex h-9 w-9 items-center justify-center rounded-md text-muted hover:bg-surface-2 hover:text-text"><MoreHorizontal className="h-5 w-5"/></span>}><button role="menuitem" onClick={()=>setActiveTab('affiliates')} className="flex w-full items-center gap-2 rounded-md px-3 py-2.5 text-left text-sm text-muted hover:bg-surface-2 hover:text-text"><Store className="h-4 w-4"/>Marketplaces e APIs</button><button role="menuitem" onClick={()=>setActiveTab('audit')} className="flex w-full items-center gap-2 rounded-md px-3 py-2.5 text-left text-sm text-muted hover:bg-surface-2 hover:text-text"><ClipboardCheck className="h-4 w-4"/>Auditoria</button><button role="menuitem" onClick={()=>setActiveTab('docs')} className="flex w-full items-center gap-2 rounded-md px-3 py-2.5 text-left text-sm text-muted hover:bg-surface-2 hover:text-text"><BookOpen className="h-4 w-4"/>Ajuda e testes</button><button role="menuitem" onClick={onRunTests} disabled={isTestingSuite} className="w-full rounded-md px-3 py-2.5 text-left text-sm text-brand-300 hover:bg-surface-2">{isTestingSuite?'Executando testes...':'Executar testes'}</button><button role="menuitem" onClick={onLogout} className="mt-1 flex w-full items-center gap-2 border-t border-border px-3 py-2.5 text-left text-sm text-muted hover:bg-surface-2 hover:text-text"><LogOut className="h-4 w-4"/>Sair</button></Dropdown></nav>

 </div></div></header>;
};